### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by akurniko**
The argument list length was not checked so exceptions were raised when not enough arguments.
Coordinates sent by GPS were converted from float to string without specifying the width, so it looked like:
60.182792000000001, 24.796084999999999
Was it intentional? Also "the fix" is a bit ugly.

Cheers,
Arseny.

### CODE REVIEW

**Comment by vr000m** [comment]
does the rounding of the co-ordinate help with parsing? if yes, then I'll merge the pull-request.

thanks for the arglen catch, since all command line params are mandatory.

**Comment by akurniko** [comment]
Well, it doesn't, just looks a bit prettier in the logs. Also it actually changes the data transmitted, I mean it looks like:
"['6.123', '12.515']" instead of:
'[6.1230000000001, 12.514999999999]'.
I think you should keep the original one.

**Comment by vr000m** [comment]
So do you want to split up the pull request? So that I just pull the arglen
one?

Regards,
Varun

---

http://www.netlab.tkk.fi/~varun

On 4.2.2013, at 17.29, Arseny Kurnikov notifications@github.com wrote:

Well, it doesn't, just looks a bit prettier in the logs. Also it actually
changes the data transmitted, I mean it looks like:
"['6.123', '12.515']" instead of:
'[6.1230000000001, '12.514999999999]'.
I think you should keep the original one.

—
Reply to this email directly or view it on
GitHubhttps://github.com/vr000m/SensorTrafficGenerator/pull/1#issuecomment-13081874.

**Comment by akurniko** [comment]
Done. Is there any automatic way to split commit? I was doing:
git reset HEAD^
modify file
git push -f.

**Pull request merged**
